apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo_frontend-route.yaml
- todo_frontend.yaml
- bitnami-controller.yaml
- todo-config.yaml
images:
- name: todo_frontend
  newName: melmanmankiewicz/todo_frontend
  newTag: 2022-04-14_13-02-14
